apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-sametime
  labels:
    app: rs-sametime-app
spec:
  template:
    metadata:
      name: sametimeapp
      labels:
        app: sametime-javaapp-app
        type: sametime-javaapp
    spec:
      containers:
        - image: amitdthakur/sametimeapp
          name: sametimeapp-container
  replicas: 3
  selector:
    matchLabels:
      type: sametime-javaapp