apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-sametime
  labels:
    app: rc-app
spec:
  template:
    metadata:
      name: sametimeapp
      labels:
        app: sametime-javaapp
    spec:
      containers:
        - image: amitdthakur/sametimeapp
          name: sametimeapp-container
  replicas: 3